// Package contexts manages the canonical global agent context and
// projects it into each linked client's global context mechanism. The
// store is one canonical file (AGENTS.md per the agents.md spec) by
// default, or an opt-in directory of rule fragments
// (~/.gridctl/context/fragments/*.md; see fragments.go). Single-file
// strategies are a dedicated file in a rules directory, an @-import
// shim line, or a marker-delimited managed block; in fragments mode,
// clients with real rules directories receive one file per fragment
// (multi-file) and everything else receives a compiled document.
// Per-project AGENTS.md files stay version-controlled in their repos and
// are out of scope. Every operation is a pure file operation; no running
// gateway is required.
package contexts

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"

	"github.com/gridctl/gridctl/pkg/project"
	"github.com/gridctl/gridctl/pkg/state"
)

// Sentinel errors callers branch on.
var (
	ErrNoCanonical     = errors.New("no canonical context file; run 'gridctl ctx init' first")
	ErrCanonicalExists = errors.New("canonical context file already exists (use --force to overwrite)")
	ErrUnknownClient   = errors.New("unknown client")
	ErrUnsupported     = errors.New("client has no global context file mechanism")
	ErrNotAvailable    = errors.New("client not initialized on this machine")
	ErrNotSynced       = errors.New("client has never been synced")
	ErrOverCap         = errors.New("rendered content exceeds the client's size limit")
)

// canonicalFileName follows the agents.md spec name so the canonical file
// is itself readable by AGENTS.md-native tools (and symlinkable into a
// dotfiles repo).
const canonicalFileName = "AGENTS.md"

// starterTemplate is the scaffold written by `ctx init` with no import
// source. Deliberately short: a bloated global file pollutes every
// client's context. Draft-labeled per the ecosystem's "starting point,
// not finished product" framing.
const starterTemplate = `# Global Agent Context

<!-- Draft starter generated by 'gridctl ctx init'. Keep this file short:
     durable cross-project preferences only. Project-specific guidance
     belongs in each repo's own AGENTS.md. -->

## Coding Style

- Prefer clarity over cleverness; keep functions small.

## Commit Conventions

- Imperative subject line, max 50 characters.

## Writing Style

- Plain prose; no filler phrases.

## Tool Preferences

- Prefer rg over grep for searching.
`

// Manager owns the canonical global context store under
// <home>/.gridctl/context and every projection into client files. All
// target paths resolve against home, so tests point it at a temp dir.
// Mutating operations serialize on mu in-process and on the engine's
// cross-process lock (shared with skill projections, so a slow context
// sync can briefly block a skill sync and vice versa).
type Manager struct {
	home  string
	store *project.Store
	mu    sync.Mutex
}

// NewManager builds a Manager rooted at the user's home directory.
func NewManager() (*Manager, error) {
	home, err := state.Home()
	if err != nil {
		return nil, fmt.Errorf("resolving home directory: %w", err)
	}
	return NewManagerWithHome(home), nil
}

// NewManagerWithHome builds a Manager rooted at an explicit home
// directory. Tests use this to stay isolated from $HOME.
func NewManagerWithHome(home string) *Manager {
	return &Manager{home: home, store: project.NewStore(home)}
}

// Dir returns the canonical store directory.
func (m *Manager) Dir() string {
	return filepath.Join(m.home, ".gridctl", "context")
}

// CanonicalPath returns the canonical global context file path.
func (m *Manager) CanonicalPath() string {
	return filepath.Join(m.Dir(), canonicalFileName)
}

// lockPath returns the projection lockfile path (the unified engine
// lockfile shared with skill projections).
func (m *Manager) lockPath() string {
	return m.store.Path()
}

// HasCanonical reports whether the canonical file exists.
func (m *Manager) HasCanonical() bool {
	info, err := os.Stat(m.CanonicalPath())
	return err == nil && !info.IsDir()
}

// CanonicalContent reads the canonical file.
func (m *Manager) CanonicalContent() (string, error) {
	data, err := os.ReadFile(m.CanonicalPath())
	if err != nil {
		if os.IsNotExist(err) {
			return "", ErrNoCanonical
		}
		return "", fmt.Errorf("reading canonical context: %w", err)
	}
	return string(data), nil
}

// SaveCanonical writes the canonical file with a backup of the previous
// revision. Content is normalized to end with exactly one newline.
func (m *Manager) SaveCanonical(content string) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.saveCanonical(content)
}

// saveCanonical is SaveCanonical without the lock, for callers that
// already hold mu (Adopt).
func (m *Manager) saveCanonical(content string) error {
	// The managed-block parser treats these strings as boundaries, so
	// canonical content containing them would corrupt every block target
	// on sync and silently truncate the canon on adopt. Refuse up front.
	for _, forbidden := range []string{beginMarker, endMarker, headerPrefix} {
		if strings.Contains(content, forbidden) {
			return fmt.Errorf("canonical content must not contain the gridctl marker %q", forbidden)
		}
	}
	if err := os.MkdirAll(m.Dir(), 0755); err != nil {
		return fmt.Errorf("creating context directory: %w", err)
	}
	if _, err := createBackup(m.CanonicalPath()); err != nil {
		return err
	}
	normalized := strings.TrimRight(normalizeNewlines(content), "\n") + "\n"
	return atomicWriteFile(m.CanonicalPath(), []byte(normalized))
}

// ScanEntry reports what already exists at one client's likely global
// context location. Scanning never writes anything.
type ScanEntry struct {
	Slug   string `json:"slug"`
	Name   string `json:"name"`
	Path   string `json:"path"`
	Exists bool   `json:"exists"`
	Size   int64  `json:"size"`
}

// Scan inspects every supported client's import location so init can
// offer adoption before scaffolding.
func (m *Manager) Scan() []ScanEntry {
	targets := Targets()
	entries := make([]ScanEntry, 0, len(targets))
	for _, t := range targets {
		path := t.importPath(m.home)
		if path == "" {
			continue
		}
		e := ScanEntry{Slug: t.Slug, Name: t.Name, Path: path}
		if info, err := os.Stat(path); err == nil && !info.IsDir() {
			e.Exists = true
			e.Size = info.Size()
		}
		entries = append(entries, e)
	}
	return entries
}

// InitFromTemplate scaffolds the starter canonical file.
func (m *Manager) InitFromTemplate(force bool) error {
	return m.initWith(starterTemplate, force)
}

// InitFromFile adopts an arbitrary file as the canonical context.
func (m *Manager) InitFromFile(path string, force bool) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("reading %s: %w", path, err)
	}
	return m.initWith(string(data), force)
}

// InitFromClient adopts a client's existing global context file as the
// canonical context. Content gridctl previously managed there (block,
// shim line, header chrome) is stripped so adoption never round-trips
// gridctl's own markers into the canon.
func (m *Manager) InitFromClient(slug string, force bool) error {
	t, err := resolveTarget(slug)
	if err != nil {
		return err
	}
	path := t.importPath(m.home)
	if path == "" {
		return fmt.Errorf("%w: %s has no global context path on this platform", ErrUnsupported, slug)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("reading %s: %w", path, err)
	}
	content := string(data)
	if inner, found, berr := extractBlockInner(content); berr == nil && found {
		// The file holds a gridctl block: everything else is the user's;
		// adopt both the block body and the surrounding content.
		stripped, _ := removeBlock(content)
		content = strings.TrimSpace(stripped) + "\n\n" + inner
	}
	content = removeShim(content, m.CanonicalPath())
	content = stripManagedChrome(t, content)
	if strings.TrimSpace(content) == "" {
		return fmt.Errorf("%s is empty after removing gridctl-managed content; nothing to import", path)
	}
	return m.initWith(content, force)
}

// initWith writes content as the canonical file, refusing to overwrite an
// existing canon unless forced (mirrors `gridctl init`).
func (m *Manager) initWith(content string, force bool) error {
	if m.HasCanonical() && !force {
		return fmt.Errorf("%w: %s", ErrCanonicalExists, m.CanonicalPath())
	}
	return m.SaveCanonical(content)
}
