package builder

import (
	"context"
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strings"
)

const PythonTemplateVersion = "python-uv-v1"

var extraNamePattern = regexp.MustCompile(`^[a-z0-9]+(?:[-_.][a-z0-9]+)*$`)
var debianPackagePattern = regexp.MustCompile(`^[a-z0-9][a-z0-9+.-]*$`)
var dependencyPattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]*(?:\[[A-Za-z0-9,._-]+\])?(?:\s*(?:===|==|!=|~=|<=|>=|<|>)\s*[A-Za-z0-9*+.!_-]+)?(?:\s*;\s*[A-Za-z0-9_. -]+(?:==|!=|<=|>=|<|>)\s*["'][A-Za-z0-9_. -]+["'])?$`)

// PythonTemplateConfig pins every external image used by generated builds.
type PythonTemplateConfig struct {
	Version      string            `json:"version"`
	PythonImages map[string]string `json:"pythonImages"`
	UVImage      string            `json:"uvImage"`
	RuntimeUID   int               `json:"runtimeUid"`
	RuntimeGID   int               `json:"runtimeGid"`
}

// Index digests preserve multi-platform Docker and Podman selection.
var defaultPythonTemplateConfig = PythonTemplateConfig{
	Version: PythonTemplateVersion,
	PythonImages: map[string]string{
		"3.10": "python:3.10.18-slim-bookworm@sha256:445b9efb2c047a7ccdb30d293fd6b1aa0f62a55062dc2b69051df91e10848749",
		"3.11": "python:3.11.13-slim-bookworm@sha256:86adf8dbadc3d6e82ee5dd2c74bec2e1c2467cdad47886280501df722372d2e1",
		"3.12": "python:3.12.11-slim-bookworm@sha256:519591d6871b7bc437060736b9f7456b8731f1499a57e22e6c285135ae657bf7",
		"3.13": "python:3.13.7-slim-bookworm@sha256:adafcc17694d715c905b4c7bebd96907a1fd5cf183395f0ebc4d3428bd22d92d",
	},
	UVImage:    "ghcr.io/astral-sh/uv:0.8.14@sha256:f3660c56d5b08d6c516360981bedc439f499b9bf37f46a216018da3777a74011",
	RuntimeUID: 10001,
	RuntimeGID: 10001,
}

// DefaultPythonTemplate returns a copy of the pinned template configuration.
func DefaultPythonTemplate() PythonTemplateConfig {
	config := defaultPythonTemplateConfig
	config.PythonImages = make(map[string]string, len(defaultPythonTemplateConfig.PythonImages))
	for version, image := range defaultPythonTemplateConfig.PythonImages {
		config.PythonImages[version] = image
	}
	return config
}

// PythonBuildSpec contains validated output-affecting inputs for generation.
type PythonBuildSpec struct {
	Python   string
	Package  string
	Version  string
	Extras   []string
	With     []string
	Packages []string
	Command  []string
	Local    bool
	Locked   bool
}

// GeneratePythonDockerfile returns the exact deterministic Dockerfile used by
// later planning and build stages.
func GeneratePythonDockerfile(ctx context.Context, spec PythonBuildSpec) (string, error) {
	if err := ctx.Err(); err != nil {
		return "", err
	}
	template := DefaultPythonTemplate()
	base, ok := template.PythonImages[spec.Python]
	if !ok {
		return "", fmt.Errorf("unsupported Python version %q", spec.Python)
	}
	extras, err := normalizeExtras(spec.Extras)
	if err != nil {
		return "", err
	}
	dependencies, err := normalizeDependencies(spec.With)
	if err != nil {
		return "", err
	}
	packages, err := normalizeDebianPackages(spec.Packages)
	if err != nil {
		return "", err
	}
	if !spec.Local && (!distributionNamePattern.MatchString(spec.Package) || spec.Version == "") {
		return "", fmt.Errorf("an exact package and version are required")
	}

	var out strings.Builder
	fmt.Fprintf(&out, "# Generated by gridctl %s\n", template.Version)
	fmt.Fprintf(&out, "FROM %s AS runtime\n", base)
	fmt.Fprintf(&out, "COPY --from=%s /uv /uvx /bin/\n", template.UVImage)
	out.WriteString("ENV UV_TOOL_BIN_DIR=/opt/gridctl/bin UV_TOOL_DIR=/opt/gridctl/tools PATH=/app/.venv/bin:/opt/gridctl/bin:$PATH UV_NO_CACHE=1\n")
	fmt.Fprintf(&out, "RUN groupadd --gid %d gridctl && useradd --uid %d --gid %d --create-home gridctl && mkdir -p /opt/gridctl/bin /opt/gridctl/tools\n", template.RuntimeGID, template.RuntimeUID, template.RuntimeGID)
	if len(packages) > 0 {
		out.WriteString("RUN apt-get update && apt-get install -y --no-install-recommends")
		for _, pkg := range packages {
			out.WriteByte(' ')
			out.WriteString(pkg)
		}
		out.WriteString(" && rm -rf /var/lib/apt/lists/*\n")
	}
	if spec.Local {
		out.WriteString("WORKDIR /app\nCOPY . /app\n")
		if spec.Locked {
			out.WriteString("RUN uv sync --locked --no-dev --no-editable")
			for _, extra := range extras {
				out.WriteString(" --extra " + extra)
			}
			out.WriteByte('\n')
			if len(dependencies) > 0 {
				out.WriteString("RUN uv pip install --python /app/.venv/bin/python")
				for _, dependency := range dependencies {
					out.WriteString(" " + shellQuote(dependency))
				}
				out.WriteByte('\n')
			}
		} else {
			install := "/app"
			installArg := install
			if len(extras) > 0 {
				install += "[" + strings.Join(extras, ",") + "]"
				installArg = shellQuote(install)
			}
			out.WriteString("RUN uv tool install " + installArg)
			for _, dependency := range dependencies {
				out.WriteString(" --with " + shellQuote(dependency))
			}
			out.WriteByte('\n')
		}
	} else {
		install := spec.Package
		if len(extras) > 0 {
			install += "[" + strings.Join(extras, ",") + "]"
		}
		install += "==" + spec.Version
		out.WriteString("RUN uv tool install " + shellQuote(install))
		for _, dependency := range dependencies {
			out.WriteString(" --with " + shellQuote(dependency))
		}
		out.WriteByte('\n')
	}
	if spec.Local {
		out.WriteString("RUN chown -R gridctl:gridctl /app /opt/gridctl\n")
	} else {
		out.WriteString("RUN chown -R gridctl:gridctl /opt/gridctl\n")
	}
	out.WriteString("USER gridctl\n")
	if len(spec.Command) > 0 {
		encoded, err := json.Marshal(spec.Command)
		if err != nil {
			return "", err
		}
		out.WriteString("CMD " + string(encoded) + "\n")
	}
	return out.String(), nil
}

func normalizeExtras(values []string) ([]string, error) {
	result := make([]string, 0, len(values))
	for _, value := range values {
		value = strings.ToLower(strings.TrimSpace(value))
		if !extraNamePattern.MatchString(value) {
			return nil, fmt.Errorf("invalid Python extra %q", value)
		}
		result = append(result, strings.ReplaceAll(strings.ReplaceAll(value, "_", "-"), ".", "-"))
	}
	return sortedUnique(result), nil
}

func normalizeDependencies(values []string) ([]string, error) {
	result := make([]string, 0, len(values))
	for _, value := range values {
		value = strings.TrimSpace(value)
		if len(value) > 256 || !dependencyPattern.MatchString(value) {
			return nil, fmt.Errorf("invalid PEP 508 dependency %q", value)
		}
		result = append(result, value)
	}
	return sortedUnique(result), nil
}

func normalizeDebianPackages(values []string) ([]string, error) {
	result := make([]string, 0, len(values))
	for _, value := range values {
		value = strings.ToLower(strings.TrimSpace(value))
		if !debianPackagePattern.MatchString(value) {
			return nil, fmt.Errorf("invalid Debian package %q", value)
		}
		result = append(result, value)
	}
	return sortedUnique(result), nil
}

func sortedUnique(values []string) []string {
	sort.Strings(values)
	result := values[:0]
	for _, value := range values {
		if len(result) == 0 || result[len(result)-1] != value {
			result = append(result, value)
		}
	}
	return result
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}
